version: 0.0
os: linux

files:  
  - source:  /
    destination: /home/ubuntu/applications/ExampleAwsCodeDeploy
    overwrite: yes
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 100
      runas : root
